version: "3"
services:
  # https://github.com/v2tec/watchtower
  # Will periodically check for image updates and hot reload image
  watchtower:
    image: v2tec/watchtower
    container_name: watchtower
    environment:
      - WATCHTOWER_NOTIFICATIONS=slack
      - WATCHTOWER_NOTIFICATION_SLACK_IDENTIFIER=Watchtower
      - "WATCHTOWER_NOTIFICATION_SLACK_HOOK_URL=${DISCORD_HOOK_URL}/slack"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30

  datomic:
    image: akiel/datomic-free:0.9.5656
    container_name: datomic
    network_mode: host
    ports:
      - 4334:4334
      - 4335:4335
      - 4336:4336
    volumes:
      - salttoday-vol:/data
      - salttoday-logs:/log

  logzio-collector:
    image: logzio/docker-collector-logs
    container_name: logzio-collector
    environment:
      - LOGZIO_TOKEN=${LOGZ_IO_TOKEN}
      - LOGZIO_URL=listener.logz.io:5015
      - matchContainerName=datomic,salttoday
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/lib/docker/containers:/var/lib/docker/containers

  salttoday:
    image: xtvaser/salttoday:latest
    container_name: salttoday
    network_mode: host
    ports:
      - 443:443
    environment:
      - KEYSTORE_PATH=/opt/keystore.jks
      - "SSL_PASSWORD=${SSL_PASSWORD}"
      - "HONEYCOMB_KEY=${HONEYCOMB_KEY}"
    volumes:
      # Use /scripts/gen-keystore.sh to generate a self-signed JKS SSL cert
      - ~/keystore.jks:/opt/keystore.jks

volumes:
  salttoday-vol:
    external: true
  salttoday-logs:
    external: true
